-- ==========================================================
-- ART GALLERY SUPABASE SCHEMA & SEED SCRIPT
-- Run this in Supabase SQL Editor to create the art_gallery table
-- and populate it with all 24 local artwork prints.
-- ==========================================================

-- 1. Create the art_gallery table if it does not exist
CREATE TABLE IF NOT EXISTS public.art_gallery (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    short_description TEXT,
    description TEXT,
    image TEXT NOT NULL,
    width INTEGER DEFAULT 1200,
    height INTEGER DEFAULT 1600,
    price NUMERIC NOT NULL DEFAULT 350,
    type TEXT CHECK (type IN ('Physical', 'Digital')) DEFAULT 'Physical',
    category TEXT CHECK (category IN ('Physical Prints', 'Digital Prints')) DEFAULT 'Physical Prints',
    availability TEXT DEFAULT 'In Stock',
    quantity INTEGER DEFAULT 25,
    year TEXT DEFAULT '2025',
    dimensions TEXT DEFAULT '24 x 36 inches',
    options JSONB DEFAULT '[]'::jsonb,
    specs JSONB DEFAULT '{}'::jsonb,
    display_order INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for fast category & sorting queries
CREATE INDEX IF NOT EXISTS idx_art_gallery_category ON public.art_gallery(category);
CREATE INDEX IF NOT EXISTS idx_art_gallery_type ON public.art_gallery(type);
CREATE INDEX IF NOT EXISTS idx_art_gallery_display_order ON public.art_gallery(display_order);
CREATE INDEX IF NOT EXISTS idx_art_gallery_created_at ON public.art_gallery(created_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.art_gallery ENABLE ROW LEVEL SECURITY;

-- 4. Public read access policy
DROP POLICY IF EXISTS "Public can view art gallery items" ON public.art_gallery;
CREATE POLICY "Public can view art gallery items" 
ON public.art_gallery FOR SELECT 
USING (true);

-- 5. Full access for authenticated & service role (and anon for development if desired)
DROP POLICY IF EXISTS "Allow all for authenticated users" ON public.art_gallery;
CREATE POLICY "Allow all for authenticated users" 
ON public.art_gallery FOR ALL 
USING (true)
WITH CHECK (true);

-- 6. Seed all 24 artwork records
INSERT INTO public.art_gallery (
    id,
    title,
    short_description,
    description,
    image,
    width,
    height,
    price,
    type,
    category,
    availability,
    quantity,
    year,
    dimensions,
    options,
    specs,
    display_order
) VALUES
(
    'art-001',
    'Serenade in Bronze & Shadow',
    'Curated fine art oil painting study highlighting warm bronze tones and dramatic shadows.',
    'An evocative study in texture, shadow, and golden illumination. Captured on medium format digital, this limited edition print explores fluid light boundaries across sculptured oil strokes.',
    '/artworks/art-001.jpg',
    1200,
    1600,
    450,
    'Physical',
    'Physical Prints',
    'Limited Edition (1/25)',
    25,
    '2025',
    '24 x 36 inches',
    '[{"id":"opt-sm","label":"16 x 24 in - Fine Art Rag Paper","price":320},{"id":"opt-md","label":"24 x 36 in - Archival Hahnemühle","price":450},{"id":"opt-lg","label":"36 x 48 in - Gallery Acrylic Mount","price":780}]'::jsonb,
    '{"paper":"Hahnemühle Photo Rag 308gsm","printing":"Pigment Archival Print","signature":"Hand-signed & numbered certificate by G. Venketram","framing":"Unframed (Ships safely rolled in wooden art tube)"}'::jsonb,
    1
),
(
    'art-002',
    'Celestial Veil',
    'High-resolution digital fluid art master file with commercial display licensing.',
    'An ethereal interplay of ambient light and liquid color streams. Designed as a high-resolution digital artwork suitable for ultra-HD luxury digital displays, architectural projections, or custom collector printing.',
    '/artworks/art-002.jpg',
    1600,
    1067,
    280,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2024',
    '8192 x 5461 px (8K Native Resolution)',
    '[{"id":"opt-dig-pers","label":"Personal Display License (JPG + PNG 8K)","price":280},{"id":"opt-dig-comm","label":"Commercial Editorial License (16-bit TIFF)","price":650}]'::jsonb,
    '{"format":"RAW / 16-Bit TIFF & Uncompressed 8K JPEG","colorSpace":"ProPhoto RGB / DCI-P3","license":"Non-Exclusive Digital Rights Certificate included","delivery":"Instant Digital File Access Link"}'::jsonb,
    2
),
(
    'art-003',
    'Monochrome Geometry',
    'Architectural shadow art print exploring minimalist form and high contrast.',
    'Stripping away color reveals pure geometric elegance. Isolating dramatic light contours across structured architectural elements and interior gallery spaces.',
    '/artworks/art-003.jpg',
    1200,
    1500,
    520,
    'Physical',
    'Physical Prints',
    'Limited Edition (3/15)',
    15,
    '2025',
    '28 x 40 inches',
    '[{"id":"opt-mono-md","label":"20 x 28 in - Exhibition Matte","price":380},{"id":"opt-mono-lg","label":"28 x 40 in - Museum Matte Fine Art","price":520},{"id":"opt-mono-xl","label":"40 x 56 in - Metallic Collector Plate","price":950}]'::jsonb,
    '{"paper":"Canson Infinity Baryta Prestige 340gsm","printing":"Epson UltraChrome Pro HD Monochromatic","signature":"Embossed Studio Seal & Signed Certificate","framing":"Custom Framed Option Available"}'::jsonb,
    3
),
(
    'art-004',
    'Velvet Horizon',
    'Cinematic art print in deep crimson hues and canvas texture.',
    'Rich textural depth meets editorial moodiness. Velvet Horizon balances abstract color fields with key lighting to create a timeless fine art piece for modern interiors.',
    '/artworks/art-004.jpg',
    1200,
    1600,
    390,
    'Physical',
    'Physical Prints',
    'In Stock',
    50,
    '2024',
    '24 x 32 inches',
    '[{"id":"opt-velvet-sm","label":"18 x 24 in - Archival Luster","price":290},{"id":"opt-velvet-md","label":"24 x 32 in - Museum Fine Art Paper","price":390},{"id":"opt-velvet-lg","label":"30 x 40 in - Stretched Fine Canvas","price":620}]'::jsonb,
    '{"paper":"Epson Premium Luster Photo Paper","printing":"Archival Pigment Printing","signature":"Hand-signed on margin","framing":"Shipped in protective art tube"}'::jsonb,
    4
),
(
    'art-005',
    'Chiaroscuro Still Life',
    'Ultra High-Definition digital masterpiece fine-tuned for digital art collectors.',
    'Inspired by Renaissance chiaroscuro master painters, this digital artwork brings dramatic shadow and highlight techniques to a classical gallery presentation.',
    '/artworks/art-005.jpg',
    1600,
    1200,
    240,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '9000 x 6750 px (9K Resolution)',
    '[{"id":"opt-chia-pers","label":"Collector Digital Package (JPG + Digital Certificate)","price":240},{"id":"opt-chia-pro","label":"High-Res Master Package (16-bit Master TIFF)","price":490}]'::jsonb,
    '{"format":"16-Bit TIFF & Ultra-HD JPEG","colorSpace":"Adobe RGB (1998)","license":"Personal & Private Gallery License","delivery":"Instant Download"}'::jsonb,
    5
),
(
    'art-006',
    'Golden Hour Symphony',
    'Warm ambient landscape art print captured in natural golden radiance.',
    'Sunlight cascades over organic textures in this warm fine art landscape print. Designed to evoke serenity, warmth, and quiet luxury in living spaces.',
    '/artworks/art-006.jpg',
    1600,
    1067,
    490,
    'Physical',
    'Physical Prints',
    'Limited Edition (2/20)',
    20,
    '2024',
    '24 x 36 inches',
    '[{"id":"opt-gold-sm","label":"16 x 24 in - Fine Art Matte","price":340},{"id":"opt-gold-md","label":"24 x 36 in - Archival Rag Fine Art","price":490},{"id":"opt-gold-lg","label":"36 x 54 in - Collector Floating Frame","price":890}]'::jsonb,
    '{"paper":"Somerset Velvet Fine Art 310gsm","printing":"Museum Grade Pigment Inkjet","signature":"Hand-signed & numbered certificate","framing":"Unframed / Rolled"}'::jsonb,
    6
),
(
    'art-007',
    'Noir Whispers',
    'Moody monochrome print featuring minimalist high-contrast architectural structure.',
    'Noir Whispers explores the depth of darkness paired with subtle highlights across modern art forms. A striking centerpiece for minimalist interiors.',
    '/artworks/art-007.jpg',
    1200,
    1800,
    360,
    'Physical',
    'Physical Prints',
    'In Stock',
    30,
    '2025',
    '20 x 30 inches',
    '[{"id":"opt-noir-sm","label":"16 x 24 in - Exhibition Matte","price":260},{"id":"opt-noir-md","label":"20 x 30 in - Baryta Satin Paper","price":360},{"id":"opt-noir-lg","label":"28 x 42 in - Aluminium Dibond Mount","price":680}]'::jsonb,
    '{"paper":"Hahnemühle Baryta FB 350gsm","printing":"B&W Carbon Pigment Ink","signature":"Hand-signed certificate included","framing":"Unframed"}'::jsonb,
    7
),
(
    'art-008',
    'Ethereal Mirage',
    'Ultra-wide digital print designed for immersive screen setups and digital frames.',
    'Soft atmospheric gradients and delicate detail merge in Ethereal Mirage. Formatted specifically for digital art collectors and smart canvas displays.',
    '/artworks/art-008.jpg',
    1600,
    900,
    310,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '7680 x 4320 px (16:9 Ultra HD)',
    '[{"id":"opt-eth-pers","label":"Standard Digital License (4K + 8K JPG)","price":310},{"id":"opt-eth-pro","label":"Master License (8K TIFF + Display Auth)","price":580}]'::jsonb,
    '{"format":"8K Ultra-HD JPG / 16-Bit TIFF","colorSpace":"Display P3","license":"Non-exclusive Digital Display Rights","delivery":"Immediate download via secure token"}'::jsonb,
    8
),
(
    'art-009',
    'Solitude in Amber',
    'Fine art ceramic study with rich golden hour tones and organic textures.',
    'Capturing a reflective composition wrapped in amber sunlight, this piece blends tactile craft narrative with museum-grade archival printing.',
    '/artworks/art-009.jpg',
    1200,
    1600,
    480,
    'Physical',
    'Physical Prints',
    'Limited Edition (5/20)',
    20,
    '2025',
    '24 x 36 inches',
    '[{"id":"opt-sol-sm","label":"16 x 24 in - Fine Art Matte","price":350},{"id":"opt-sol-md","label":"24 x 36 in - Hahnemühle Bamboo 290gsm","price":480},{"id":"opt-sol-lg","label":"32 x 48 in - Floating Frame Canvas","price":820}]'::jsonb,
    '{"paper":"Hahnemühle Bamboo Eco-FineArt 290gsm","printing":"Pigment Archival Print","signature":"Hand-signed & embossed by G. Venketram","framing":"Unframed / Collector Tube"}'::jsonb,
    9
),
(
    'art-010',
    'Prism & Marble',
    'High-resolution digital abstract study exploring refraction and fluid geometric symmetry.',
    'An architectural exploration of light refraction on polished marble surfaces. A clean digital master print for modern office and gallery spaces.',
    '/artworks/art-010.jpg',
    1600,
    1200,
    260,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2024',
    '8000 x 6000 px (48 MP Digital Master)',
    '[{"id":"opt-prism-pers","label":"Personal Display File (High-Res JPG)","price":260},{"id":"opt-prism-comm","label":"Architectural License (16-Bit RAW TIFF)","price":540}]'::jsonb,
    '{"format":"16-Bit Uncompressed TIFF & 8K JPEG","colorSpace":"Adobe RGB (1998)","license":"Commercial / Personal Display License","delivery":"Instant Digital File Access Link"}'::jsonb,
    10
),
(
    'art-011',
    'Symphony of Silk',
    'High-fashion textile fine art print emphasizing fluid movement and rich woven layers.',
    'Sculptural fabric dynamics in motion. Symphony of Silk captures flowing waves of crimson silk in vibrant detail.',
    '/artworks/art-011.jpg',
    1200,
    1500,
    560,
    'Physical',
    'Physical Prints',
    'Limited Edition (2/10)',
    10,
    '2025',
    '30 x 40 inches',
    '[{"id":"opt-silk-sm","label":"20 x 28 in - Archival Cotton Rag","price":420},{"id":"opt-silk-md","label":"30 x 40 in - Gallery Metallic Print","price":560},{"id":"opt-silk-lg","label":"40 x 54 in - Acrylic Glass Mount","price":1100}]'::jsonb,
    '{"paper":"Canson Infinity Rag Photologique 310gsm","printing":"Epson UltraChrome HDX 10-Color Pigment","signature":"Hand-signed with numbered studio seal","framing":"Unframed"}'::jsonb,
    11
),
(
    'art-012',
    'Echoes of Antiquity',
    'Classical gallery artwork frame inspired by ancient temple motifs.',
    'Echoes of Antiquity bridges heritage craftsmanship with contemporary fine art photography. Featuring rich muted undertones and intricate traditional details.',
    '/artworks/art-012.jpg',
    1200,
    1600,
    640,
    'Physical',
    'Physical Prints',
    'Collector Edition (1/5)',
    5,
    '2025',
    '32 x 48 inches',
    '[{"id":"opt-echo-md","label":"24 x 36 in - Fine Art Matte","price":490},{"id":"opt-echo-lg","label":"32 x 48 in - Museum Archival Print","price":640},{"id":"opt-echo-xl","label":"40 x 60 in - Hand-framed Master Piece","price":1350}]'::jsonb,
    '{"paper":"Hahnemühle Museum Etching 350gsm","printing":"Pigment Archival Print","signature":"Hand-signed certificate of authenticity","framing":"Unframed"}'::jsonb,
    12
),
(
    'art-013',
    'Nebula Dreams',
    'Digital cosmic atmosphere masterpiece for digital frame installations.',
    'Deep indigo and violet light hues intermingle to form a dreamlike cosmic visual piece. Ideal for ambient high-end screen displays.',
    '/artworks/art-013.jpg',
    1600,
    900,
    320,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '7680 x 4320 px (8K UHD)',
    '[{"id":"opt-neb-pers","label":"Collector Digital Pack (8K JPEG)","price":320},{"id":"opt-neb-pro","label":"Master Digital License (RAW + TIFF)","price":620}]'::jsonb,
    '{"format":"16-Bit TIFF & Uncompressed JPEG","colorSpace":"DCI-P3 / Wide Gamut","license":"Non-exclusive Digital Display Rights","delivery":"Instant File Access"}'::jsonb,
    13
),
(
    'art-014',
    'Terracotta Silence',
    'Warm earthen ceramic fine art print featuring warm clay and shadow balance.',
    'Earthen tones of terracotta paired with stark shadow lines create a soothing, grounded aesthetic suited for luxury residential interior spaces.',
    '/artworks/art-014.jpg',
    1200,
    1600,
    410,
    'Physical',
    'Physical Prints',
    'In Stock',
    40,
    '2024',
    '24 x 36 inches',
    '[{"id":"opt-terra-sm","label":"18 x 24 in - Exhibition Satin","price":310},{"id":"opt-terra-md","label":"24 x 36 in - Museum Smooth Fine Art","price":410},{"id":"opt-terra-lg","label":"30 x 45 in - Canvas Wrap","price":690}]'::jsonb,
    '{"paper":"Hahnemühle Photo Rag Ultra Smooth 305gsm","printing":"Epson UltraChrome HD Pigment","signature":"Hand-signed by G. Venketram","framing":"Unframed"}'::jsonb,
    14
),
(
    'art-015',
    'Minimalist Horizon',
    'Subtle horizon landscape with expansive atmosphere and soft pastel gradient.',
    'A meditation on space and stillness. Minimalist Horizon uses subtle pastel sky gradients to create an expansive sense of peace.',
    '/artworks/art-015.jpg',
    1600,
    1067,
    390,
    'Physical',
    'Physical Prints',
    'In Stock',
    35,
    '2024',
    '24 x 36 inches',
    '[{"id":"opt-[#1c1a17]-sm","label":"16 x 24 in - Archival Matte","price":290},{"id":"opt-[#1c1a17]-md","label":"24 x 36 in - Fine Art Rag","price":390},{"id":"opt-[#1c1a17]-lg","label":"36 x 54 in - Aluminium Mounted","price":790}]'::jsonb,
    '{"paper":"Somerset Velvet 310gsm","printing":"Archival Pigment Printing","signature":"Hand-signed certificate","framing":"Unframed / Rolled"}'::jsonb,
    15
),
(
    'art-016',
    'Opulent Golden Tapestry',
    'Ultra High-Definition fine art piece featuring framed golden masterwork.',
    'Detailed macro view of handcrafted golden accents and fine art frame detail. Captured with precision optics to reveal rich light luminescence.',
    '/artworks/art-016.jpg',
    1200,
    1600,
    290,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '8000 x 6000 px (8K Resolution)',
    '[{"id":"opt-op-pers","label":"Personal Display Digital File","price":290},{"id":"opt-op-pro","label":"Master Commercial File (16-Bit TIFF)","price":580}]'::jsonb,
    '{"format":"16-Bit TIFF & Uncompressed JPEG","colorSpace":"ProPhoto RGB","license":"Digital Rights Certificate Included","delivery":"Instant Download"}'::jsonb,
    16
),
(
    'art-017',
    'Prismatic Waves',
    'Vibrant gradient waves forming dynamic abstract visual poetry for digital frames.',
    'Fluid spectrum interplay designed for modern ambient display. Formatted in high-bit depth color gamut for premium digital canvases.',
    '/artworks/art-017.jpg',
    1600,
    1067,
    340,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '8192 x 5461 px (8K UHD)',
    '[{"id":"opt-prismw-1","label":"Standard Digital File (8K JPG)","price":340},{"id":"opt-prismw-2","label":"Master Display Pack (16-Bit TIFF)","price":640}]'::jsonb,
    '{"format":"16-Bit TIFF & Uncompressed 8K JPEG","colorSpace":"Display P3 / Adobe RGB","license":"Personal & Private Gallery License","delivery":"Instant File Access"}'::jsonb,
    17
),
(
    'art-018',
    'Verdant Echoes',
    'Botanical museum print exploring lush organic forms and textured paper grain.',
    'Archival fine art print celebrating natural botanical forms. Printed on heavy cotton rag paper to preserve delicate green tones.',
    '/artworks/art-018.jpg',
    1200,
    1600,
    420,
    'Physical',
    'Physical Prints',
    'In Stock',
    30,
    '2025',
    '24 x 36 inches',
    '[{"id":"opt-verd-1","label":"16 x 24 in - Fine Art Matte","price":310},{"id":"opt-verd-2","label":"24 x 36 in - Archival Hahnemühle","price":420},{"id":"opt-verd-3","label":"32 x 48 in - Floating Canvas Frame","price":790}]'::jsonb,
    '{"paper":"Hahnemühle German Etching 310gsm","printing":"Pigment Archival Print","signature":"Hand-signed & numbered certificate","framing":"Unframed / Rolled Tube"}'::jsonb,
    18
),
(
    'art-019',
    'Azure Modernism',
    'Bold expressionist oil on canvas print with deep lapis and cobalt tones.',
    'Dynamic blue strokes merge with structural geometry. A dramatic focal artwork for residential living rooms and executive suites.',
    '/artworks/art-019.jpg',
    1200,
    1600,
    510,
    'Physical',
    'Physical Prints',
    'Limited Edition (4/15)',
    15,
    '2025',
    '28 x 40 inches',
    '[{"id":"opt-azur-1","label":"20 x 28 in - Exhibition Cotton","price":380},{"id":"opt-azur-2","label":"28 x 40 in - Museum Rag Paper","price":510},{"id":"opt-azur-3","label":"36 x 52 in - Stretched Gallery Canvas","price":920}]'::jsonb,
    '{"paper":"Somerset Velvet Fine Art 310gsm","printing":"Epson UltraChrome HDX 10-Color Pigment","signature":"Hand-signed with studio seal","framing":"Unframed"}'::jsonb,
    19
),
(
    'art-020',
    'Pastel Reverie',
    'Soft atmospheric color study designed for ambient high-definition digital displays.',
    'Gently blending blush, cream, and sky hues to create a calming spatial atmosphere in contemporary spaces.',
    '/artworks/art-020.jpg',
    1600,
    1067,
    270,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2024',
    '7680 x 4320 px (8K UHD)',
    '[{"id":"opt-pas-1","label":"Personal Display Pack (JPG)","price":270},{"id":"opt-pas-2","label":"Commercial Architectural Rights","price":560}]'::jsonb,
    '{"format":"16-Bit TIFF & 8K JPEG","colorSpace":"sRGB / DCI-P3","license":"Non-Exclusive Digital Rights","delivery":"Instant Link"}'::jsonb,
    20
),
(
    'art-021',
    'Luminous Atelier',
    'Archival pigment print capturing classical artist palette textures and pigments.',
    'Close-up textural exploration of raw paint pigments and oil mediums. Printed with ultra-fine pigment ink for lifetime color fidelity.',
    '/artworks/art-021.jpg',
    1200,
    1600,
    460,
    'Physical',
    'Physical Prints',
    'In Stock',
    25,
    '2025',
    '24 x 36 inches',
    '[{"id":"opt-lum-1","label":"18 x 24 in - Exhibition Matte","price":340},{"id":"opt-lum-2","label":"24 x 36 in - Fine Art Cotton Rag","price":460},{"id":"opt-lum-3","label":"30 x 45 in - Metal Sublimation Plate","price":830}]'::jsonb,
    '{"paper":"Canson Infinity Rag Photologique 310gsm","printing":"Archival Pigment Printing","signature":"Hand-signed & numbered certificate","framing":"Unframed"}'::jsonb,
    21
),
(
    'art-022',
    'Minimalist Solitude',
    'Clean monochromatic wall art print with fine art matte finish.',
    'Quiet spatial geometry isolating light, shadow, and architectural silence. Designed for minimalist modern interior collectors.',
    '/artworks/art-022.jpg',
    1200,
    1600,
    380,
    'Physical',
    'Physical Prints',
    'In Stock',
    40,
    '2024',
    '20 x 30 inches',
    '[{"id":"opt-min-1","label":"16 x 24 in - Archival Smooth","price":280},{"id":"opt-min-2","label":"20 x 30 in - Museum Matte Paper","price":380},{"id":"opt-min-3","label":"28 x 42 in - Aluminum Mounted","price":690}]'::jsonb,
    '{"paper":"Hahnemühle Photo Rag Ultra Smooth 305gsm","printing":"Carbon Monochromatic Pigment","signature":"Hand-signed certificate","framing":"Unframed"}'::jsonb,
    22
),
(
    'art-023',
    'Spectral Canvas',
    'Ultra HD 8K digital masterpiece celebrating fluid art motion and light.',
    'Complex light caustics and fluid color dynamics frozen in microscopic detail. Formatted for high-end digital galleries and ultra-large displays.',
    '/artworks/art-023.jpg',
    1600,
    1067,
    330,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '8192 x 5461 px (8K Native)',
    '[{"id":"opt-spec-1","label":"Collector Digital Package (JPG)","price":330},{"id":"opt-spec-2","label":"Exclusive Master Package (RAW + TIFF)","price":670}]'::jsonb,
    '{"format":"16-Bit Master TIFF & 8K JPEG","colorSpace":"ProPhoto RGB","license":"Digital Display Rights Certificate","delivery":"Instant Download"}'::jsonb,
    23
),
(
    'art-024',
    'Chrono Spectrum',
    'Geometric digital art print rendered for luxury home wall screens and collectors.',
    'Precision light geometry and prismatic color field study. Perfect companion artwork for multi-screen art setups.',
    '/artworks/art-024.jpg',
    1600,
    1067,
    295,
    'Digital',
    'Digital Prints',
    'Instant Download',
    999,
    '2025',
    '7680 x 4320 px (8K UHD)',
    '[{"id":"opt-chrono-1","label":"Standard Digital File","price":295},{"id":"opt-chrono-2","label":"Commercial Architectural License","price":590}]'::jsonb,
    '{"format":"16-Bit TIFF & Uncompressed JPEG","colorSpace":"Display P3","license":"Non-Exclusive License Included","delivery":"Instant Download"}'::jsonb,
    24
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    image = EXCLUDED.image,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    price = EXCLUDED.price,
    type = EXCLUDED.type,
    category = EXCLUDED.category,
    availability = EXCLUDED.availability,
    quantity = EXCLUDED.quantity,
    year = EXCLUDED.year,
    dimensions = EXCLUDED.dimensions,
    options = EXCLUDED.options,
    specs = EXCLUDED.specs,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();
